---
# Deploy Gitea Git service

- name: Create Gitea data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_items:
    - /opt/gitea/data
    - /opt/gitea/config
  tags: [gitea, directories]

- name: Create Gitea docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/gitea/docker-compose.yml
    mode: '0640'
  tags: [gitea, config]
  notify: restart gitea

- name: Enable and start Gitea service
  systemd:
    name: "docker-compose@gitea"
    state: started
    enabled: yes
    daemon_reload: yes
  tags: [gitea, services]
