---
- name: Test gRPC endpoint
  hosts: mocks
  gather_facts: false
  become: false

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - build-essential
          - python3-dev
        state: present
      when: ansible_os_family == 'Debian'

    - name: Create test directory
      file:
        path: /tmp/grpc_test
        state: directory

    - name: Copy test files
      copy:
        src: "{{ item }}"
        dest: /tmp/grpc_test/
      with_items:
        - test_grpc.py
        - ../../protos/
      register: files_copied

    - name: Create virtual environment
      command: python3 -m venv /tmp/grpc_test/venv
      args:
        creates: /tmp/grpc_test/venv

    - name: Install Python packages
      pip:
        name:
          - grpcio
          - grpcio-tools
          - protobuf
          - python-dateutil
          - prometheus-client
        virtualenv: /tmp/grpc_test/venv
        virtualenv_command: python3 -m venv

    - name: Generate gRPC code
      command: /tmp/grpc_test/venv/bin/python -m grpc_tools.protoc -I /tmp/grpc_test/protos --python_out=/tmp/grpc_test --grpc_python_out=/tmp/grpc_test /tmp/grpc_test/protos/example.proto
      args:
        creates: /tmp/grpc_test/example_pb2.py

    - name: Test gRPC server
      command: /tmp/grpc_test/venv/bin/python /tmp/grpc_test/test_grpc.py
      register: grpc_test
      changed_when: false
      failed_when: false
      environment:
        PYTHONPATH: /tmp/grpc_test

    - name: Show gRPC test result
      debug:
        var: grpc_test.stdout_lines

    - name: Fail if gRPC test failed
      fail:
        msg: "gRPC test failed - could not connect to server"
      when: grpc_test.rc != 0
