---
- name: Test Taskinity Invoice Processors
  hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  vars:
    project_root: "{{ lookup('env', 'PWD') }}"
    python_version: 3.8

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python{{ python_version }}
          - python{{ python_version }}-venv
          - tesseract-ocr
          - tesseract-ocr-eng
          - tesseract-ocr-pol
          - poppler-utils
          - ghostscript
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
      tags: [deps, system]

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: python{{ python_version }} -m venv {{ project_root }}/venv
        creates: "{{ project_root }}/venv/bin/activate"
      tags: [venv]

    - name: Install Python dependencies
      pip:
        requirements: "{{ project_root }}/requirements.txt"
        virtualenv: "{{ project_root }}/venv"
        virtualenv_python: "python{{ python_version }}"
      tags: [deps, python]

    - name: Install email-invoices dependencies
      pip:
        requirements: "{{ project_root }}/examples/email-invoices/requirements.txt"
        virtualenv: "{{ project_root }}/venv"
      tags: [deps, email]

    - name: Install web-invoices dependencies
      pip:
        requirements: "{{ project_root }}/examples/web-invoices/requirements.txt"
        virtualenv: "{{ project_root }}/venv"
      tags: [deps, web]

    - name: Create test directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ project_root }}/test_data/emails"
        - "{{ project_root }}/test_data/web_invoices"
        - "{{ project_root }}/test_data/output"
        - "{{ project_root }}/logs"
      tags: [setup]

    - name: Copy test configuration files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      with_items:
        - {
            src: "templates/email-invoices/.env.j2",
            dest: "{{ project_root }}/examples/email-invoices/.env",
          }
        - {
            src: "templates/web-invoices/.env.j2",
            dest: "{{ project_root }}/examples/web-invoices/.env",
          }
      tags: [config]

    - name: Run email processor tests
      command: "{{ project_root }}/venv/bin/pytest {{ project_root }}/examples/email-invoices/tests/ -v"
      environment:
        PYTHONPATH: "{{ project_root }}"
      register: email_test_result
      changed_when: false
      tags: [test, email]

    - name: Run web processor tests
      command: "{{ project_root }}/venv/bin/pytest {{ project_root }}/examples/web-invoices/tests/ -v"
      environment:
        PYTHONPATH: "{{ project_root }}"
      register: web_test_result
      changed_when: false
      tags: [test, web]

    - name: Show test results
      debug:
        msg:
          - "Email Processor Tests: {{ 'PASSED' if email_test_result.rc == 0 else 'FAILED' }}"
          - "Web Processor Tests: {{ 'PASSED' if web_test_result.rc == 0 else 'FAILED' }}"
      tags: [test]
