---
- name: Test WebRTC endpoint
  hosts: mocks
  gather_facts: false
  become: false

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-selenium
          - chromium-chromedriver
          - chromium-browser
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Python packages
      pip:
        name:
          - selenium
          - webdriver-manager
          - requests
        state: present

    - name: Create test directory
      file:
        path: /tmp/webrtc_test
        state: directory

    - name: Copy test script
      copy:
        src: test_webrtc.py
        dest: /tmp/webrtc_test/test_webrtc.py
        mode: "0755"

    - name: Run WebRTC test
      command: python3 /tmp/webrtc_test/test_webrtc.py
      register: webrtc_test
      changed_when: false
      failed_when: false
      environment:
        DISPLAY: ":99"

    - name: Show WebRTC test result
      debug:
        var: webrtc_test.stdout_lines

    - name: Fail if WebRTC test failed
      fail:
        msg: "WebRTC test failed - could not connect to signaling server"
      when: webrtc_test.rc != 0
