version: "3.8"

services:
  rtsp-server:
    build: ./rtsp/docker
    container_name: rtsp-mock
    ports:
      - "8554:8554" # RTSP
      - "8888:8888" # HTTP
    restart: unless-stopped
    networks:
      - mock-network

  http-server:
    build: ./http/docker
    container_name: http-mock
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - mock-network

  webrtc-server:
    build: ./webrtc/docker
    container_name: webrtc-mock
    ports:
      - "8443:8443"
    restart: unless-stopped
    networks:
      - mock-network

  grpc-server:
    build: ./grpc/docker
    container_name: grpc-mock
    ports:
      - "50051:50051" # gRPC
      - "8000:8000" # Prometheus metrics
    restart: unless-stopped
    networks:
      - mock-network
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import grpc; channel = grpc.insecure_channel('localhost:50051'); import example_pb2, example_pb2_grpc; stub = example_pb2_grpc.GreeterStub(channel); response = stub.SayHello(example_pb2.HelloRequest(name='healthcheck'), timeout=5)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  mqtt-broker:
    build: ./mqtt/docker
    container_name: mqtt-mock
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # MQTT over WebSocket
    restart: unless-stopped
    networks:
      - mock-network

networks:
  mock-network:
    driver: bridge
